# Generated by Django 3.2.5 on 2021-12-23 12:05

import apps.ota_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware', models.FileField(upload_to=apps.ota_api.models.firmware_file_name)),
                ('version', models.CharField(max_length=100)),
                ('comentarios', models.CharField(max_length=200)),
                ('received_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('mac_addr', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('observacoes', models.CharField(max_length=100)),
                ('firmware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ota_api.firmware')),
            ],
        ),
    ]
